// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import path from "path";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: path.join('prisma'),
  migrations: {
    path: path.join('prisma', 'migrations'),
    seed: `bun ${path.join(process.cwd(), 'prisma', 'seeds', 'index.ts')}`,
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
